apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy-react-app
  template:
    metadata:
      labels:
        app: swiggy-react-app
    spec:
      containers:
      - name: app
        image: subhash1302/swiggy-react-app:latest
        ports:
        - containerPort: 3000
